### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by boydachina** [DarleySoares/Data-requests-about-COVID-19-in-Brazil#1]
A fonte dos dados está fora do ar desde o dia 19, você percebeu? se souber outra fonte vou ficar aqui acompanhando

**Comment by DarleySoares** [comment]
Sim Victor, pelo que percebi o Ministério da Saúde tirou o dashboard de casos do COVID-19 do ar, estou verificando outra base, porém sem sucesso

**Comment by boydachina** [comment]
achei esse source aqui: https://sigageomarketing.com.br/coronavirus/ eu só não sei de onde eles pegam esses dados

**Comment by DarleySoares** [comment]
Obrigado pela fonte de dados, mas como disse, não sabemos a procedência dos dados, se estão corretos, se a atualização está constante...

**Comment by boydachina** [comment]
Pelo que sei, é uma empresa bem reconhecida no mercado, estão fazendo a atualização dos dados todos os dias, o único problema é a procedência dos dados, provavelmente devem pegar nas noticias que circulam, mas dizem que a fonte é do ministério da saúde.

**Comment by DarleySoares** [comment]
Acredito que não seja do Ministério da Saúde, porque se você analisar os dados do arquivo json, existem informações que não existiam pelo MS, como por exemplo essas taxas. Entretanto, irem colocar uma segunda opção de código no repositório daqui a pouco para pegar os dados por lá

**Comment by boydachina** [comment]
eu to fazendo isso também, mas estou enrolado devido aos dados estarem em um script js.

**Comment by DarleySoares** [comment]
Coloquei um segundo código já, ele está puxando as informações corretas.

**Comment by boydachina** [comment]
achei o source oficial do ministério da saúde covid.saude.gov.br

**Comment by DarleySoares** [comment]
Boa noite! Eu estou pegando as informações agora do site do bing (óbitos) e do site da globo (casos confirmados), no qual existem um detalhamento melhor, com relação a localização, por exemplo cidades.

**Comment by boydachina** [comment]
cara, como você acha a fonte dos dados? tipo você sabe o site que tem os dados, mas você acha o /data dele? eu ainda não sei como encontrar isso

**Comment by DarleySoares** [comment]
A partir do site você clica com o botão direito, depois inspecionar. Em seguida você vai na categoria Network e atualiza a página. Em 'nome' vai aparecer alguns arquivos que ele trás, ai você busca nele.

**Comment by boydachina** [comment]
Muito obrigado, descobri como faz, ajudou bastante, quando fui ver nesse site que mandou, os dados estão como unauthorized, vou procurar como resolver isso

**Comment by boydachina** [comment]
Isso não funciona em todos não né eu tô tentando de um site para capturar das cidades do meu estado nesse site https://covid.lais.ufrn.br/ e quando fiz isso não achei nenhum json no site, e eu fiquei sem saber como faz

**Comment by DarleySoares** [comment]
Depende de como a estrutura do site e dos dados é estabelecida. Nos casos que utilizei as visualizações foram montadas no front end, então a partir do dados de um arquivo, eles inseriram na página. Pelo que observei desse site, talvez os dados são montados no back end, assim não existe um arquivo com os dados.
